services:
  - type: web
    name: keystroke-auth
    runtime: python
    buildCommand: pip install -r requirements.txt && python model/train_base.py
    startCommand: gunicorn app:app -c gunicorn.conf.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 5000